# Generated by Django 3.2.12 on 2022-04-08 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferFranceBleu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('cat', models.CharField(max_length=300)),
                ('color', models.CharField(max_length=300)),
                ('creation_date', models.DateField()),
                ('postes', models.CharField(max_length=300)),
                ('mob', models.CharField(max_length=300)),
                ('direction', models.CharField(max_length=300)),
            ],
        ),
        migrations.RemoveField(
            model_name='offer',
            name='france_bleu',
        ),
        migrations.AlterField(
            model_name='offer',
            name='creation_date',
            field=models.DateField(),
        ),
    ]
