# Generated by Django 3.2.12 on 2022-04-11 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0003_offerfrancebleu_ville'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='url',
            field=models.CharField(default=0, max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offerfrancebleu',
            name='url',
            field=models.CharField(default='', max_length=400),
            preserve_default=False,
        ),
    ]
