# Generated by Django 3.2.12 on 2022-04-11 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0004_auto_20220411_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='creation_date',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='offerfrancebleu',
            name='creation_date',
            field=models.CharField(max_length=300),
        ),
    ]
